// <auto-generated />
using System;
using Day14Lab1PokeDex.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Day14Lab1PokeDex.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230327103125_PublicMoves")]
    partial class PublicMoves
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Day14Lab1PokeDex.Models.Element", b =>
                {
                    b.Property<int>("ElementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ElementID"));

                    b.Property<string>("ElementName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PokemonID")
                        .HasColumnType("int");

                    b.HasKey("ElementID");

                    b.HasIndex("PokemonID");

                    b.ToTable("Elements");
                });

            modelBuilder.Entity("Day14Lab1PokeDex.Models.ElementSensibility", b =>
                {
                    b.Property<int>("ElementSensibilityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ElementSensibilityID"));

                    b.Property<int>("ElementId")
                        .HasColumnType("int");

                    b.Property<int>("ElementSensibilityPerCent")
                        .HasColumnType("int");

                    b.HasKey("ElementSensibilityID");

                    b.HasIndex("ElementId");

                    b.ToTable("ElementsSensibilities");
                });

            modelBuilder.Entity("Day14Lab1PokeDex.Models.Move", b =>
                {
                    b.Property<int>("MoveID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MoveID"));

                    b.Property<int>("ElementID")
                        .HasColumnType("int");

                    b.Property<bool>("IsAttack")
                        .HasColumnType("bit");

                    b.Property<bool>("IsElementary")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPriority")
                        .HasColumnType("bit");

                    b.Property<int>("MoveAttackUp")
                        .HasColumnType("int");

                    b.Property<int>("MoveClass")
                        .HasColumnType("int");

                    b.Property<int>("MoveDefenseUp")
                        .HasColumnType("int");

                    b.Property<int>("MoveHitPoints")
                        .HasColumnType("int");

                    b.Property<int>("MoveLifePointsUp")
                        .HasColumnType("int");

                    b.Property<int>("MoveMaxRepeat")
                        .HasColumnType("int");

                    b.Property<string>("MoveName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovePrecision")
                        .HasColumnType("int");

                    b.Property<int>("MoveSpeedUp")
                        .HasColumnType("int");

                    b.Property<int?>("PokemonID")
                        .HasColumnType("int");

                    b.HasKey("MoveID");

                    b.HasIndex("ElementID");

                    b.HasIndex("PokemonID");

                    b.ToTable("Moves");
                });

            modelBuilder.Entity("Day14Lab1PokeDex.Models.Picture", b =>
                {
                    b.Property<int>("PictureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PictureID"));

                    b.Property<string>("PictureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RawData")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("PictureID");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("Day14Lab1PokeDex.Models.Pokemon", b =>
                {
                    b.Property<int>("PokemonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PokemonID"));

                    b.Property<bool>("IsEgg")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFemale")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLegendary")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMale")
                        .HasColumnType("bit");

                    b.Property<int?>("PictureID")
                        .HasColumnType("int");

                    b.Property<int>("PokemonAttack")
                        .HasColumnType("int");

                    b.Property<int>("PokemonDefense")
                        .HasColumnType("int");

                    b.Property<int>("PokemonLevel")
                        .HasColumnType("int");

                    b.Property<int>("PokemonLifePoints")
                        .HasColumnType("int");

                    b.Property<string>("PokemonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PokemonSpecialAttack")
                        .HasColumnType("int");

                    b.Property<int>("PokemonSpecialDefense")
                        .HasColumnType("int");

                    b.Property<int>("PokemonSpeeed")
                        .HasColumnType("int");

                    b.Property<int>("PokemonStatus")
                        .HasColumnType("int");

                    b.Property<int>("PokemonWeight")
                        .HasColumnType("int");

                    b.Property<int>("PokemonXP")
                        .HasColumnType("int");

                    b.HasKey("PokemonID");

                    b.HasIndex("PictureID");

                    b.ToTable("Pokemons");
                });

            modelBuilder.Entity("Day14Lab1PokeDex.Models.Element", b =>
                {
                    b.HasOne("Day14Lab1PokeDex.Models.Pokemon", null)
                        .WithMany("Elements")
                        .HasForeignKey("PokemonID");
                });

            modelBuilder.Entity("Day14Lab1PokeDex.Models.ElementSensibility", b =>
                {
                    b.HasOne("Day14Lab1PokeDex.Models.Element", "Element")
                        .WithMany()
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");
                });

            modelBuilder.Entity("Day14Lab1PokeDex.Models.Move", b =>
                {
                    b.HasOne("Day14Lab1PokeDex.Models.Element", "Element")
                        .WithMany()
                        .HasForeignKey("ElementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Day14Lab1PokeDex.Models.Pokemon", null)
                        .WithMany("Moves")
                        .HasForeignKey("PokemonID");

                    b.Navigation("Element");
                });

            modelBuilder.Entity("Day14Lab1PokeDex.Models.Pokemon", b =>
                {
                    b.HasOne("Day14Lab1PokeDex.Models.Picture", "Picture")
                        .WithMany()
                        .HasForeignKey("PictureID");

                    b.Navigation("Picture");
                });

            modelBuilder.Entity("Day14Lab1PokeDex.Models.Pokemon", b =>
                {
                    b.Navigation("Elements");

                    b.Navigation("Moves");
                });
#pragma warning restore 612, 618
        }
    }
}
