// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPiKiller.Models;

#nullable disable

namespace WebAPiKiller.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230320091107_initialDB")]
    partial class initialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("WebAPiKiller.Models.Killer", b =>
                {
                    b.Property<int>("KillerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInJail")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KillerDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KillerKilled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KillerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("KillerID");

                    b.ToTable("Killers");
                });
#pragma warning restore 612, 618
        }
    }
}
