// <auto-generated />
using Day13Lab1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Day13Lab1.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("Day13Lab1.Models.Address", b =>
                {
                    b.Property<int>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MyAnagraphicAnagraphicID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AddressID");

                    b.HasIndex("MyAnagraphicAnagraphicID");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Day13Lab1.Models.Anagraphic", b =>
                {
                    b.Property<int>("AnagraphicID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VAT")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AnagraphicID");

                    b.ToTable("Anagraphics");
                });

            modelBuilder.Entity("Day13Lab1.Models.Address", b =>
                {
                    b.HasOne("Day13Lab1.Models.Anagraphic", "MyAnagraphic")
                        .WithMany()
                        .HasForeignKey("MyAnagraphicAnagraphicID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MyAnagraphic");
                });
#pragma warning restore 612, 618
        }
    }
}
